# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 711, 571))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mutationTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.mutationTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.mutationTextEdit.setObjectName("mutationTextEdit")
        self.gridLayout.addWidget(self.mutationTextEdit, 0, 2, 1, 1)
        self.populationSizeTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.populationSizeTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.populationSizeTextEdit.setObjectName("populationSizeTextEdit")
        self.gridLayout.addWidget(self.populationSizeTextEdit, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.crossoverTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.crossoverTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.crossoverTextEdit.setObjectName("crossoverTextEdit")
        self.gridLayout.addWidget(self.crossoverTextEdit, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.symbolSet1TextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.symbolSet1TextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.symbolSet1TextEdit.setObjectName("symbolSet1TextEdit")
        self.gridLayout.addWidget(self.symbolSet1TextEdit, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 2, 1, 1)
        self.symbolSetSizeTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.symbolSetSizeTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.symbolSetSizeTextEdit.setObjectName("symbolSetSizeTextEdit")
        self.gridLayout.addWidget(self.symbolSetSizeTextEdit, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 10, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.numberOfGenerationsTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.numberOfGenerationsTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.numberOfGenerationsTextEdit.setObjectName("numberOfGenerationsTextEdit")
        self.gridLayout.addWidget(self.numberOfGenerationsTextEdit, 2, 2, 1, 1)
        self.symbolSet2TextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.symbolSet2TextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.symbolSet2TextEdit.setObjectName("symbolSet2TextEdit")
        self.gridLayout.addWidget(self.symbolSet2TextEdit, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 1, 1, 1)
        self.bestSolutionUntilNowTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.bestSolutionUntilNowTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.bestSolutionUntilNowTextEdit.setObjectName("bestSolutionUntilNowTextEdit")
        self.gridLayout_2.addWidget(self.bestSolutionUntilNowTextEdit, 0, 2, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_2.addWidget(self.stopButton, 1, 2, 1, 1)
        self.solutionLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.solutionLabel.setObjectName("solutionLabel")
        self.gridLayout_2.addWidget(self.solutionLabel, 0, 1, 1, 1)
        self.fitnessPlotTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.fitnessPlotTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.fitnessPlotTextEdit.setObjectName("fitnessPlotTextEdit")
        self.gridLayout_2.addWidget(self.fitnessPlotTextEdit, 3, 2, 1, 1)
        self.validationTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.validationTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.validationTextEdit.setObjectName("validationTextEdit")
        self.gridLayout_2.addWidget(self.validationTextEdit, 4, 2, 1, 1)
        self.validationButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.validationButton.setObjectName("validationButton")
        self.gridLayout_2.addWidget(self.validationButton, 4, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Probability of mutation"))
        self.label_3.setText(_translate("MainWindow", "Probability of crossover"))
        self.label_7.setText(_translate("MainWindow", "Symbol Set 1"))
        self.label_8.setText(_translate("MainWindow", "Symbol Set 2"))
        self.label_4.setText(_translate("MainWindow", "Number of generations"))
        self.label_5.setText(_translate("MainWindow", "Size of symbol sets"))
        self.runButton.setText(_translate("MainWindow", "Run algorithm"))
        self.label_2.setText(_translate("MainWindow", "Population size"))
        self.label_6.setText(_translate("MainWindow", "Fitness plot"))
        self.stopButton.setText(_translate("MainWindow", "Stop algorithm"))
        self.solutionLabel.setText(_translate("MainWindow", "Best Solution until now"))
        self.validationButton.setText(_translate("MainWindow", "Run validation test "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

