# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1547, 990)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1491, 921))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mutationTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.mutationTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.mutationTextEdit.setObjectName("mutationTextEdit")
        self.gridLayout.addWidget(self.mutationTextEdit, 0, 2, 1, 1)
        self.crossoverTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.crossoverTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.crossoverTextEdit.setObjectName("crossoverTextEdit")
        self.gridLayout.addWidget(self.crossoverTextEdit, 1, 2, 1, 1)
        self.symbolSet1TextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.symbolSet1TextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.symbolSet1TextEdit.setObjectName("symbolSet1TextEdit")
        self.gridLayout.addWidget(self.symbolSet1TextEdit, 5, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.symbolSet2TextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.symbolSet2TextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.symbolSet2TextEdit.setObjectName("symbolSet2TextEdit")
        self.gridLayout.addWidget(self.symbolSet2TextEdit, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.populationSizeTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.populationSizeTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.populationSizeTextEdit.setObjectName("populationSizeTextEdit")
        self.gridLayout.addWidget(self.populationSizeTextEdit, 3, 2, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 10, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.symbolSetSizeTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.symbolSetSizeTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.symbolSetSizeTextEdit.setObjectName("symbolSetSizeTextEdit")
        self.gridLayout.addWidget(self.symbolSetSizeTextEdit, 4, 2, 1, 1)
        self.numberOfGenerationsTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.numberOfGenerationsTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.numberOfGenerationsTextEdit.setObjectName("numberOfGenerationsTextEdit")
        self.gridLayout.addWidget(self.numberOfGenerationsTextEdit, 2, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.iterationsTextField = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.iterationsTextField.setObjectName("iterationsTextField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.iterationsTextField)
        self.runHillButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.runHillButton.setObjectName("runHillButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.runHillButton)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.sizeSymbolSetHillTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.sizeSymbolSetHillTextEdit.setObjectName("sizeSymbolSetHillTextEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sizeSymbolSetHillTextEdit)
        self.symbolSet1HillTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.symbolSet1HillTextEdit.setObjectName("symbolSet1HillTextEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.symbolSet1HillTextEdit)
        self.symbolSet2HillTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.symbolSet2HillTextEdit.setObjectName("symbolSet2HillTextEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.symbolSet2HillTextEdit)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.line_3 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.psoIterationsText = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.psoIterationsText.setObjectName("psoIterationsText")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.psoIterationsText)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.psoParticlesText = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.psoParticlesText.setObjectName("psoParticlesText")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.psoParticlesText)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.psoSizeSSymbolSet = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.psoSizeSSymbolSet.setObjectName("psoSizeSSymbolSet")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.psoSizeSSymbolSet)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.psoSymbolSet1 = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.psoSymbolSet1.setObjectName("psoSymbolSet1")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.psoSymbolSet1)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.psoSymbolSet2 = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.psoSymbolSet2.setObjectName("psoSymbolSet2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.psoSymbolSet2)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.psoWText = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.psoWText.setObjectName("psoWText")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.psoWText)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.psoC1Text = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.psoC1Text.setObjectName("psoC1Text")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.psoC1Text)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.psoC2Text = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.psoC2Text.setObjectName("psoC2Text")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.psoC2Text)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.psoNeighbourhoodSizeText = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.psoNeighbourhoodSizeText.setObjectName("psoNeighbourhoodSizeText")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.psoNeighbourhoodSizeText)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.line_4 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.solutionLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.solutionLabel.setObjectName("solutionLabel")
        self.gridLayout_2.addWidget(self.solutionLabel, 0, 0, 1, 1)
        self.bestSolutionUntilNowTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.bestSolutionUntilNowTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.bestSolutionUntilNowTextEdit.setObjectName("bestSolutionUntilNowTextEdit")
        self.gridLayout_2.addWidget(self.bestSolutionUntilNowTextEdit, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 2, 1, 1)
        self.layoutPlot = QtWidgets.QVBoxLayout()
        self.layoutPlot.setObjectName("layoutPlot")
        self.gridLayout_2.addLayout(self.layoutPlot, 8, 2, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_2.addWidget(self.stopButton, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.validationButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.validationButton.setObjectName("validationButton")
        self.verticalLayout.addWidget(self.validationButton)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.verticalLayout, 8, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 6, 2, 1, 1)
        self.loadingLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.loadingLabel.setText("")
        self.loadingLabel.setObjectName("loadingLabel")
        self.gridLayout_2.addWidget(self.loadingLabel, 5, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1547, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Size of symbol sets"))
        self.label_4.setText(_translate("MainWindow", "Number of generations"))
        self.label_3.setText(_translate("MainWindow", "Probability of crossover"))
        self.label_7.setText(_translate("MainWindow", "Symbol Set 1"))
        self.label.setText(_translate("MainWindow", "Probability of mutation"))
        self.label_2.setText(_translate("MainWindow", "Population size"))
        self.runButton.setText(_translate("MainWindow", "Run Evolutionary Algorithm"))
        self.label_8.setText(_translate("MainWindow", "Symbol Set 2"))
        self.label_9.setText(_translate("MainWindow", "Number of iteration"))
        self.runHillButton.setText(_translate("MainWindow", "Run Hill Climbing"))
        self.label_10.setText(_translate("MainWindow", "Size of symbol set"))
        self.label_11.setText(_translate("MainWindow", "Symbol set 1"))
        self.label_12.setText(_translate("MainWindow", "Symbol set 2"))
        self.label_14.setText(_translate("MainWindow", "No of Iterations"))
        self.label_15.setText(_translate("MainWindow", "Number of particles"))
        self.label_23.setText(_translate("MainWindow", "Size symbol set"))
        self.label_17.setText(_translate("MainWindow", "symbolSet1"))
        self.label_18.setText(_translate("MainWindow", "symbolSet2"))
        self.label_19.setText(_translate("MainWindow", "W"))
        self.label_20.setText(_translate("MainWindow", "C1"))
        self.label_21.setText(_translate("MainWindow", "C2"))
        self.label_22.setText(_translate("MainWindow", "Size neighbourhood"))
        self.pushButton_2.setText(_translate("MainWindow", "Run PSO"))
        self.solutionLabel.setText(_translate("MainWindow", "Best Solution until now"))
        self.label_13.setText(_translate("MainWindow", "Red - data | Blue-mean | Green-standard deviation"))
        self.stopButton.setText(_translate("MainWindow", "Stop algorithm"))
        self.validationButton.setText(_translate("MainWindow", "Run validation testEA "))
        self.pushButton.setText(_translate("MainWindow", "Run Validation PSO"))

